# This blueprint tells Render to use our custom build script.
# It is the most direct and reliable way to deploy.

services:
  - name: document-classifier
    # We explicitly define this as a web service.
    type: web
    # The runtime environment is Python.
    env: python
    # CRITICAL: This tells Render to run our build.sh script to set everything up.
    # It will install Tesseract, Poppler, and all Python libraries.
    buildCommand: "./build.sh"
    # The start command remains the same.
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

